spring:
  datasource:
    url: jdbc:mysql://localhost:3306/woojik?sessionVariables=FOREIGN_KEY_CHECKS=0
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        connection:
          session_settings: SET FOREIGN_KEY_CHECKS=0;

server:
  port: 8080

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}
